apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: api-fd-create-start
  title: API FD Create
  description: Submit an API front door ticket to initiate the API design and onboarding process!
  tags:
    - experimental
    - Architecture enablement
spec:
  owner: ArchE
  templater: Pablo A.
  type: service
  path: "."
    # these are the steps which are rendered in the frontend with the form input
 

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: '/api-tools'
